name = "daily-brew"
main = "src/index.ts"
compatibility_date = "2026-02-14"

[vars]
ALLOWED_ORIGIN = "https://coco-timer.pages.dev"

[[kv_namespaces]]
binding = "KV_DAILY_BREW"
id = "450ef4b292ae41968d145b327fcf87c9"

[triggers]
crons = ["0 19 * * *"]
